[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "123456"
database = "go-rabbitmq-consume"
maxOpenConn = 50
maxIdleConn = 5
timeout = 10 #单位秒

[rabbitmq]
host = "127.0.0.1"
port = "5672"
user = "guest"
password = "guest"
vhost = ""

[log]
logPath = "/var/go-rabbitmq-consume/runtime" # 日志路径
maxSize = 500 #单个文件最大size，单位MB
maxBackups = 100 #最大过期日志保留的个数
maxAge = 30 #保留过期文件的最大时间间隔,单位是天
compress = false #是否需要压缩滚动日志, 使用的 gzip 压缩

[system]
pidPath = "/var/go-rabbitmq-consume/runtime" # 主进程路径，必须
configCheckInterval = 60 #监控任务变化变化的时间间隔，单位秒
queueMsgCountCheckInterval = 60 #单位秒，队列消息数量检测时间间隔，连续3次达到设置的预警值，则预警。设置为0不检测
queueConsumerCountCheckInterval = 60 #单位秒，消费者数量检测间隔，设置为0不检测
enableWebhook = true # 出现异常是否推送消息
webhookUrl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxx" #webhook地址

